pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - status-success=codecov/patch
      - base=develop
      - label!=work-in-progress
      - label=ready-to-merge
    actions:
      merge:
        method: merge
      delete_head_branch: {}