default_stages: [push]

repos:
  - repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pytest tests
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        stages: [push, commit]

      - id: mypy
        name: Check mypy static types match
        entry: mypy instapi
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        stages: [push, commit]
